/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SearchStrategy = {
  Exact: "exact",
  Semantic: "semantic",
} as const;
export type SearchStrategy = ClosedEnum<typeof SearchStrategy>;

/** @internal */
export const SearchStrategy$inboundSchema: z.ZodNativeEnum<
  typeof SearchStrategy
> = z.nativeEnum(SearchStrategy);

/** @internal */
export const SearchStrategy$outboundSchema: z.ZodNativeEnum<
  typeof SearchStrategy
> = SearchStrategy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SearchStrategy$ {
  /** @deprecated use `SearchStrategy$inboundSchema` instead. */
  export const inboundSchema = SearchStrategy$inboundSchema;
  /** @deprecated use `SearchStrategy$outboundSchema` instead. */
  export const outboundSchema = SearchStrategy$outboundSchema;
}

