# Kubernetes secrets configuration
# NOTE: This is a template - actual secrets should be managed via external secret management
apiVersion: v1
kind: Secret
metadata:
  name: localization-app-secrets
  namespace: localization-app
type: Opaque
stringData:
  # OpenAI API configuration
  OPENAI_API_KEY: "REPLACE_WITH_ACTUAL_KEY"
  
  # Session and JWT secrets
  SESSION_SECRET: "REPLACE_WITH_SECURE_SESSION_SECRET"
  JWT_SECRET: "REPLACE_WITH_SECURE_JWT_SECRET"
  
  # OAuth secrets (if using)
  GOOGLE_CLIENT_SECRET: "REPLACE_WITH_GOOGLE_CLIENT_SECRET"
  MICROSOFT_CLIENT_SECRET: "REPLACE_WITH_MICROSOFT_CLIENT_SECRET"
  
  # Database secrets (if using external DB)
  DATABASE_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
  
  # External service API keys
  SENTRY_DSN: "REPLACE_WITH_SENTRY_DSN"
  
  # AWS S3 credentials (if using)
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_SECRET_KEY"

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: localization-app-config
  namespace: localization-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  MAX_UPLOAD_MB: "25"
  LOG_LEVEL: "info"
  
  # Redis configuration
  REDIS_URL: "redis://redis:6379"
  
  # OAuth configuration (client IDs are not sensitive)
  GOOGLE_CLIENT_ID: "REPLACE_WITH_GOOGLE_CLIENT_ID"
  MICROSOFT_CLIENT_ID: "REPLACE_WITH_MICROSOFT_CLIENT_ID"
  
  # AWS S3 configuration
  S3_REGION: "us-east-1"
  S3_BUCKET: "localization-app-files"
  
  # Timeout configurations
  OPENAI_TIMEOUT: "30000"
  OPENAI_BATCH_TIMEOUT: "120000"
  OPENAI_LONG_TIMEOUT: "300000"
  
  # Circuit breaker configurations
  OPENAI_ERROR_THRESHOLD: "50"
  OPENAI_RESET_TIMEOUT: "60000"
  OPENAI_VOLUME_THRESHOLD: "10"
  OPENAI_CAPACITY: "100"
  
  # Queue worker concurrency
  TRANSLATION_LONG_WORKER_CONCURRENCY: "2"
  FILE_PROCESSING_WORKER_CONCURRENCY: "1"
  BATCH_TRANSLATION_WORKER_CONCURRENCY: "3"
  
  # File retention
  DEFAULT_FILE_TTL_HOURS: "24"
  BACKUP_RETENTION_DAYS: "30"
